name: Security Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏èheckout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK (recommended for Spring Boot)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Build Spring Boot application
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Build Spring Boot app
        working-directory: SpringAOPDemo
        run: mvn clean package -DskipTests
      # Run OWASP Dependency-Check
      - name: Run Security Scan
        run: |
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
          unzip dependency-check-6.5.3-release.zip
          chmod +x dependency-check/bin/dependency-check.sh
          ./dependency-check/bin/dependency-check.sh \
            --project SpringBoot-Security-Scan \
            --scan target \
            --format HTML \
            --out report \
            --disableAssembly \
            -v

      # Upload security report
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report
